### ISSUE TITLE
nudging people to help them stay at 2m or more

### ISSUE THREAD

**Issue by SimonTilley** [DP-3T/documents#157] opened 2020-04-13 11:08 UTC
I had an idea that nudging people with their phones might help them social distance, especially if they have to work ... construction workers and the like and might inadvertently get close. If a phone alerted you that anther phone was within 2m it would help set a new norm. Vibration followed by alarm etc…..Could this option be added to your app that you are developing? Or would it need a completly different solution?
    Just a thought!
Simon

**Comment by lbarman** [comment] 2020-04-13 11:13
Hi Simon, thanks for your input. This seems to be a duplicate of https://github.com/DP-3T/documents/issues/40. If so, could we merge the issues (close this one and continue the discussion there) ?

**Comment by SimonTilley** [comment] 2020-04-13 11:38
Fine by me!

 

All the best

Simon

**Comment by cascremers** [comment] 2020-04-13 11:41
Okay, closing this one and referring to #40 instead! Thank you.

**Closed by cascremers** 2020-04-13 11:41 UTC
Labels: app, suggested extension
