### ISSUE TITLE
Why not using direct public key exchange?

### ISSUE THREAD

**Issue by gagarine** [DP-3T/documents#34] opened 2020-04-05 10:51 UTC
I don't understand the advantage of generating ephIDs instead of directly broadcasting public key (and rotate those key) like https://github.com/AndreasGassmann/WeTrace

Isn't 128bites key enough as we just want messages to be secure for a short period.

Using key exchange you open a communication channel and can send a more complex message.

**Comment by i7mist** [comment] 2020-04-06 06:03
i think the problem is malicious people make pretend to be another person and report an infected case. In WeTrace, anyone that has received an id from a person nearby can fake their identity, while in this system it won’t happen, because only the ephIDs are broadcasted, and the original key is not shared with people nearby in regular conditions.

**Comment by gagarine** [comment] 2020-04-06 19:03
But a malicious user can record another use ephID and broadcast it.  I'm missing something? 

I think this is actually an unsolvable problem without some kind of central authority than distribute the identity. I'm wrong?

**Comment by i7mist** [comment] 2020-04-07 06:56
You are right. A malicious user can fake contact events by recording and broadcasting ephID. This risk is discussed in their [white paper](https://github.com/DP-3T/documents/blob/master/DP3T%20White%20Paper.pdf). You can see it in the "Summary of central/decentral design trade-offs" table right before the conclusion.

And the advantage of ephID that I was talking about is a different thing. Consider this hypothetical example. A and B are two people that have been in close contact recently, so both of them have recorded the ephID of the other person. A potential issue here is that B could be a malicious user and want to report A as "infected", when A is actually not. However, this can be prevented by the use of ephID. Because to report an infected case, the user needs to upload the original key, rather than the ephID generated with the original key, and the original key is never broadcasted, so B won't know it.

**Comment by kennypaterson** [comment] 2020-04-07 14:56
Indeed, this question is addressed in our FAQ, P4 but thanks for sparking the discussion.

**Closed by kennypaterson** 2020-04-07 14:56 UTC
Labels: protocol
