### ISSUE TITLE
Design 2 - is there a truncate missing

### ISSUE THREAD

**Issue by dirkx** [DP-3T/documents#98] opened 2020-04-09 14:18 UTC
Stored locally in design 2 is:

       The hashed identity H(EphID||t) , 

The backend populates the cocoo filter with:

    TRUNCATE128(H(H(seed)||t)).  

Is that correct - should that not be 
  
   H( TRUNCATE128(H(seed)) || t)

??

**Comment by cascremers** [comment] 2020-04-09 15:13
Duplicate of #77  , see there for solution.

**Closed by cascremers** 2020-04-09 15:13 UTC
Labels: protocol
