### ISSUE TITLE
Asymmetric signing of EphIDs to mitigate fake contacts risk

### ISSUE THREAD

**Issue by inaitana** [DP-3T/documents#38] opened 2020-04-05 14:21 UTC
It looks like the EphIDs are broadcasted in plain-text, while the "secret key" is just used as a seed for generation.
EphID spoofing is fairly easy in this scenario, and this could potentially lead to targeted attacks where fake contacts between an individual and known at-risk infected individuals can be simulated.

To mitigate this, each user could be assigned a private key, and broadcasted data could contain the EphID, the timestamp and a signature which can be verified with his public key.
The timestamp can be synchronized by the app itself with good tolerance of eventual device-specific offsets.

This packet signature could be an easy mitigation for fake contact attacks (and possibly lead to other good side effects), though they would still be theorically possible by instantanous recording and remote replication of broadcasted packets.

**Comment by jaromil** [comment] 2020-04-06 07:11
I agree with the need you point out, but EphIDs are broadcasted as Bluetooth Low Energy beacons, for which the technical limit of size is 16bytes.

Considering this is high entropy content, such a small size is likely not suitable to include a timestamp and an ECDH signature, not even using compression.

**Comment by inaitana** [comment] 2020-04-06 09:05
You are right, I misread the part of the document that stated it.

But, as far as I can find, the advertised BLE payload size in v4 is 37 bytes (in v5 it's 255).
This includes the 6 bytes "MAC" which can't always be arbitrarily set, but leaves 31 bytes available.
Part of these 31 bytes is usually a 16 bytes service UUID, but there's still space.

I don't know if the 16 bytes stated in the document are the result of some cross-compatibility evaluation, or if they just come from the standard UUID size.

Let's pretend 16 bytes is the limit.
If the EphIDs were sized down to 8 bytes, there would still be a 10^19 codomain for the hashing function. With a good distribution, this would leave > 1 billion values for every person on Earth.
The timestamp would be 4 bytes, leaving 4 bytes for the signature. It would look more like a check digit then a signature, and might be guessed with a bruteforce, but with some rate limiting policy it might be reliable enough.
Of course this could lead to a blinding attack, forcing a temporary ban of an EphID by bruteforcing it, but it would still be far less probable and effective than the obvious fake contact attack the system is currently open to.

I know this is pushing the limits and might have undesired effects, but I think it might deserve to be weighted.
Especially if the payload size is actually 31 bytes, which would be a game changer.

**Comment by maskeeter** [comment] 2020-04-06 22:26
Bluetooth 4.0 (supported by most devices) GAP protocol max payload size is actually 31 bytes.

**Comment by maskeeter** [comment] 2020-04-06 22:26
By the way, There's solution already implemented by google for this exact problem:
[Ephemeral Identifiers: Mitigating Tracking & Spoofing Threats to BLE Beacons](https://developers.google.com/beacons/eddystone-eid-preprint.pdf )

**Comment by jaromil** [comment] 2020-04-07 10:45
I rest my backing of the argument of signing as it is well answered by the new FAQ:
https://github.com/DP-3T/documents/blob/master/FAQ.md#p4-why-is-the-system-not-using-public-key-cryptography-when-broadcasting-identifiers

**Comment by inaitana** [comment] 2020-04-07 12:33
No it is not. That FAQ is about public key cryptography as in encryption, not as in signing.

That FAQ describes a session with keys exchange, I guess the aim would be to encrypt the payload. That would of course be too complex to be reliable.

What this issue is about is signing the advertised data, which remains cleartext. No additional exchange would be needed.

**Comment by kennypaterson** [comment] 2020-04-07 16:09
While generating the DP-3T proposal, we considered many different cryptographic techniques. We ruled out solutions which would require the deployment of a public key infrastructure (PKI). My understanding of your approach is that it would require a form of PKI, otherwise it would seem to be difficult to verify the authenticity of public keys. This is on top of the severe space limits in BLE beacons.

**Comment by cascremers** [comment] 2020-04-07 16:34
If the signature key doesn't change over time, wouldn't this allow easy tracking (of infected and non infected users) by anyone who knows the public key?

**Comment by inaitana** [comment] 2020-04-07 16:50
@kennypaterson The payload just needs to include the signature, which can be just a few bytes if spoofed bruteforcing packets bursts can be detected (this is something that would need to be done regardless).

The public key can then be shared together with the SK_t, since only infected users' packets need to be confirmed authentic.

@cascremers The current proposal already allows to link EphIDs of the same infected user once the SK_t is published, so this would not be a regression.
If any solution to avoid published infected EphIDs grouping is implemented (such as publishing mixed sets of EphIDs instead than users SK_ts), the public key would become a crucial linking factor.
Then a different public key for each EphID would be needed.

**Comment by inaitana** [comment] 2020-04-07 18:10
@kennypaterson A public key infrastructure would not be needed since key pairs would be generated on end users devices.
The proof needed is that the signed Bluetooth packet advertising the EphID was generated by the same device who is reporting his SK_t.
If reporting the SK_t is already considered a proof of identity, no infrastructure is needed.

**Comment by cascremers** [comment] 2020-04-07 18:14
The signing seems like a strong regression to me, since it would additionally allow linking of non-infected users, and also infected users before their infection, and after they changed their sk.

Note that reporting the SK_t is not considered a proof of identity in our design at all.

**Comment by inaitana** [comment] 2020-04-07 18:57
@cascremers Yes it would allow linking of non-infected users, so a different public key would need to generated for each EphID. This might possibly be overcomplicated.

By proof of identity I meant that the device which is reporting the infected SK_t is acknowledged to be the device of the infected user who generated the SK_t (and, in my proposal, the public keys).
No third party can report the SK_t of another user, which is not publicly known.
This is why I stated a self generated public key would work, since the report is already trusted. The reported public key is then granted to be the original one, who signed the original packets broadcasting the EphIDs and didn't sign the fake contacts.

If EphIDs were reported in place of SK_ts, it would be extremely easy to file fake reports of a third party's EphID, so reports would be untrusted.

And in this scenario self generated public keys can't be trusted, since any EphIDs could be signed with any public key, broadcasted and then fakely reported together with the fake public key.

**Comment by dariofiore** [comment] 2020-04-09 09:18
As far as I understand, this problem is already solved by the current protocols (see the "Fake contact events" paragraphs in the security analysis), at least to some degree, if one considers the epoch t to be the timestamp (this is more clear in the Design2).

**Comment by inaitana** [comment] 2020-04-09 11:22
Yes it is now strongly mitigated in the new Design 2, and in a much smarter way;)

**Comment by cascremers** [comment] 2020-04-13 12:20
Since this now seems to be resolved, closing the issue.

**Closed by cascremers** 2020-04-13 12:20 UTC
Labels: protocol
